apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cross-cutting-concerns
  namespace: ostock
spec:
  interval: 1m0s
  ref:
    branch: develop
  secretRef:
    name: ssh-rsa-credentials
  url: ssh://github.com/biya-bi/ostock-cross-cutting-concerns.git
