apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: license-service
  namespace: ostock
spec:
  interval: 1m0s
  ref:
    branch: develop
  secretRef:
    name: ssh-rsa-credentials
  url: ssh://github.com/biya-bi/ostock-license-service.git
