apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/path
      value: ./dev/sops-age
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    name: ostock-sops-age
    namespace: infra
- patch: |-
    - op: replace
      path: /data/jwt-issuer-uri
      value: https://devkeycloak.nguiland.org/realms/ostock
  target:
    version: v1
    kind: ConfigMap
    name: keycloak
    namespace: ostock
- patch: |-
    - op: replace
      path: /spec/chart/spec/valuesFiles/0
      value: values.dev.yaml
  target:
    group: helm.toolkit.fluxcd.io
    version: v2
    kind: HelmRelease
    name: angular-frontend
    namespace: ostock
- patch: |-
    - op: replace
      path: /spec/chart/spec/valuesFiles/0
      value: values.dev.yaml
  target:
    group: helm.toolkit.fluxcd.io
    version: v2
    kind: HelmRelease
    name: config-service
    namespace: ostock
- patch: |-
    - op: replace
      path: /spec/chart/spec/valuesFiles/0
      value: values.dev.yaml
  target:
    group: helm.toolkit.fluxcd.io
    version: v2
    kind: HelmRelease
    name: eureka-service
    namespace: ostock
- patch: |-
    - op: replace
      path: /spec/chart/spec/valuesFiles/0
      value: values.dev.yaml
  target:
    group: helm.toolkit.fluxcd.io
    version: v2
    kind: HelmRelease
    name: gateway-service
    namespace: ostock
- patch: |-
    - op: replace
      path: /spec/chart/spec/valuesFiles/0
      value: values.dev.yaml
  target:
    group: helm.toolkit.fluxcd.io
    version: v2
    kind: HelmRelease
    name: license-service
    namespace: ostock
- patch: |-
    - op: replace
      path: /spec/chart/spec/valuesFiles/0
      value: values.dev.yaml
  target:
    group: helm.toolkit.fluxcd.io
    version: v2
    kind: HelmRelease
    name: organization-service
    namespace: ostock
