apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ostock-sops-age
  namespace: infra
spec:
  dependsOn:
    - name: sops-age
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./dev/sops-age
  prune: true
  sourceRef:
    kind: GitRepository
    name: ostock-secrets
