apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: config-service
  namespace: ostock
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/config-service
      sourceRef:
        kind: GitRepository
        name: ostock-helm
      interval: 10m
      valuesFiles:
        - ./charts/config-service/values.yaml
