apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway-service
  namespace: ostock
spec:
  interval: 10m
  chart:
    spec:
      chart: '.'
      sourceRef:
        kind: GitRepository
        name: gateway-service-chart
      interval: 10m
      reconcileStrategy: Revision
      valuesFiles:
        - values.yaml
