apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: maven-lib
  namespace: ostock
spec:
  providerRef:
    name: maven-lib
  eventSeverity: info
  eventMetadata:
    contextDir: '.'
  eventSources:
    - kind: GitRepository
      name: cross-cutting-concerns
    - kind: GitRepository
      name: orm
