apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: config-service
  namespace: ostock
  labels:
    category: microservice
spec:
  providerRef:
    name: maven-helm
  eventSeverity: info
  eventMetadata:
    mavenContextDir: '.'
    helmChartReleaseNamespace: ostock
    helmChartsDir: config-service
    helmChartRepoUrl: git@github.com:biya-bi/ostock-helm.git
    helmChartRepoRevision: develop
  eventSources:
    - kind: GitRepository
      name: config-service
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: eureka-service
  namespace: ostock
  labels:
    category: microservice
spec:
  providerRef:
    name: maven-helm
  eventSeverity: info
  eventMetadata:
    mavenContextDir: '.'
    helmChartReleaseNamespace: ostock
    helmChartsDir: eureka-service
    helmChartRepoUrl: git@github.com:biya-bi/ostock-helm.git
    helmChartRepoRevision: develop
  eventSources:
    - kind: GitRepository
      name: eureka-service
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: gateway-service
  namespace: ostock
  labels:
    category: microservice
spec:
  providerRef:
    name: maven-helm
  eventSeverity: info
  eventMetadata:
    mavenContextDir: '.'
    helmChartReleaseNamespace: ostock
    helmChartsDir: gateway-service
    helmChartRepoUrl: git@github.com:biya-bi/ostock-helm.git
    helmChartRepoRevision: develop
  eventSources:
    - kind: GitRepository
      name: gateway-service
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: license-service
  namespace: ostock
  labels:
    category: microservice
spec:
  providerRef:
    name: maven-helm
  eventSeverity: info
  eventMetadata:
    mavenContextDir: '.'
    helmChartReleaseNamespace: ostock
    helmChartsDir: license-service
    helmChartRepoUrl: git@github.com:biya-bi/ostock-helm.git
    helmChartRepoRevision: develop
  eventSources:
    - kind: GitRepository
      name: license-service
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: organization-service
  namespace: ostock
  labels:
    category: microservice
spec:
  providerRef:
    name: maven-helm
  eventSeverity: info
  eventMetadata:
    mavenContextDir: '.'
    helmChartReleaseNamespace: ostock
    helmChartsDir: organization-service
    helmChartRepoUrl: git@github.com:biya-bi/ostock-helm.git
    helmChartRepoRevision: develop
  eventSources:
    - kind: GitRepository
      name: organization-service
