apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: maven-helm
  namespace: ostock
spec:
  providerRef:
    name: maven-helm
  eventSeverity: info
  eventMetadata:
    mavenContextDir: '.'
    helmChartReleaseNamespace: ostock
    helmChartsDir: charts
    helmChartRepoUrl: git@github.com:biya-bi/ostock-helm.git
  eventSources:
    - kind: GitRepository
      name: config-service
    - kind: GitRepository
      name: eureka-service
    - kind: GitRepository
      name: organization-service
    - kind: GitRepository
      name: licensing-service
    - kind: GitRepository
      name: gateway-service
