apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: config-service
  namespace: ostock
spec:
  providerRef:
    name: maven-helm
  eventSeverity: info
  eventMetadata:
    mavenContextDir: '.'
    helmChartReleaseNamespace: ostock
    helmChartsDir: '.'
    helmChartRepoUrl: git@github.com:biya-bi/ostock-config-service-chart.git
  eventSources:
    - kind: GitRepository
      name: config-service
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: eureka-service
  namespace: ostock
spec:
  providerRef:
    name: maven-helm
  eventSeverity: info
  eventMetadata:
    mavenContextDir: '.'
    helmChartReleaseNamespace: ostock
    helmChartsDir: '.'
    helmChartRepoUrl: git@github.com:biya-bi/ostock-eureka-service-chart.git
  eventSources:
    - kind: GitRepository
      name: eureka-service
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: gateway-service
  namespace: ostock
spec:
  providerRef:
    name: maven-helm
  eventSeverity: info
  eventMetadata:
    mavenContextDir: '.'
    helmChartReleaseNamespace: ostock
    helmChartsDir: '.'
    helmChartRepoUrl: git@github.com:biya-bi/ostock-gateway-service-chart.git
  eventSources:
    - kind: GitRepository
      name: gateway-service
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: licensing-service
  namespace: ostock
spec:
  providerRef:
    name: maven-helm
  eventSeverity: info
  eventMetadata:
    mavenContextDir: '.'
    helmChartReleaseNamespace: ostock
    helmChartsDir: '.'
    helmChartRepoUrl: git@github.com:biya-bi/ostock-licensing-service-chart.git
  eventSources:
    - kind: GitRepository
      name: licensing-service
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: organization-service
  namespace: ostock
spec:
  providerRef:
    name: maven-helm
  eventSeverity: info
  eventMetadata:
    mavenContextDir: '.'
    helmChartReleaseNamespace: ostock
    helmChartsDir: '.'
    helmChartRepoUrl: git@github.com:biya-bi/ostock-organization-service-chart.git
  eventSources:
    - kind: GitRepository
      name: organization-service
