apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: angular-frontend
  namespace: ostock
spec:
  providerRef:
    name: node-helm
  eventSeverity: info
  eventMetadata:
    nodeContextDir: '.'
    nodeBuildOutputDir: 'dist'
    helmChartReleaseNamespace: ostock
    helmChartsDir: '.'
    helmChartRepoUrl: git@github.com:biya-bi/ostock-angular-frontend-chart.git
  eventSources:
    - kind: GitRepository
      name: angular-frontend
